models.py
from app import db

class Booking(db.Model):
    __tablename__ = "bookings"

    id = db.Column(db.Integer, primary_key=True)
    booking_name = db.Column(db.String(64))
    email = db.Column(db.String(64))
    phone_number = db.Column(db.String(64))
    number_of_guests = db.Column(db.Integer)
    booking_date = db.Column(db.DateTime)
    accepted = db.Column(db.Boolean)
    tableid = db.Column(db.Integer, db.ForeignKey('tables.id'))
    slotid = db.Column(db.Integer, db.ForeignKey('slots.id'))

class Slot(db.Model):

    __tablename__ = 'slots'

    id = db.Column(db.Integer, primary_key=True)
    start_time = db.Column(db.String(7))
    end_time = db.Column(db.String(7))
    bookings = db.relationship('Booking', backref="slot")

class Table(db.Model):
    __tablename__= "tables"

    id = db.Column(db.Integer, primary_key=True)
    seats = db.Column(db.String(64))

models/Booking.py
from app import db

class Booking(db.Model):
    __tablename__ = "bookings"

    id = db.Column(db.Integer, primary_key=True)
    booking_name = db.Column(db.String(64))
    email = db.Column(db.String(64))
    phone_number = db.Column(db.String(64))
    number_of_guests = db.Column(db.Integer)
    booking_time = db.Column(db.DateTime)
    accepted = db.Column(db.Boolean)
    tableid = db.Column(db.Integer, db.ForeignKey('tables.id'))
    slotid = db.Column(db.Integer, db.ForeignKey('slots.id'))

    def __repr__(self):
        return f'<Booking {self.id}: {self.booking_name}>'

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://blairscott@localhost:5432/good_restaurant2"
app.config["SQLALCHEMY_ECHO"] = True
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from models import Slot, Table, Booking
from controllers.resaurant_controller import restaurant_blueprint

app.register_blueprint(restaurant_blueprint)

@app.route('/')
def home():
    return "Hello World"

if __name__ == '__main__':
    app.run(debug=True)

controllers/resaurant_controller.py
from flask import Flask, redirect, render_template, Blueprint, request
from app import db
from models import Booking, Slot, Table

restaurant_blueprint = Blueprint("restaurant", __name__)

@restaurant_blueprint.route('/')
def index():
    return render_template('index.jinja')

@restaurant_blueprint.route('/the_good_restaurant/book')
def show_book():
    slots = Slot.query.all()
    bookings = Booking.query.all()
    return render_template('/customer_view/book.jinja', slots=slots, bookings=bookings)

@restaurant_blueprint.route('/the_good_restaurant/book_slot', methods=['POST'])
def show_book_slot():
    date = request.form['date']
    bookings = Booking.query.filter(Booking.booking_date == date)
    slots=Slot.query.all()
    available_slots = []
    for slot in slots:
        if slot.id not in [booking.slotid for booking in bookings]: 
            available_slots.append(slot)
    
    return render_template('/customer_view/book_slot.jinja', slots=available_slots, date=date)

@restaurant_blueprint.route('/the_good_restaurant/booking-confirmed')
def booking_confirmed():
    bookings = Booking.query.all()
    return render_template('/customer_view/booking_confirmed.jinja', bookings=bookings)

@restaurant_blueprint.route('/the_good_restaurant/bookings')
def show_bookings():
    slots = Slot.query.all()
    bookings = Booking.query.all()
    tables = Table.query.all()
    return render_template('/staff-view/bookings.jinja', slots=slots, bookings=bookings, tables=tables)

@restaurant_blueprint.route("/the_good_restaurant/book", methods=['POST'])
def create_booking():
    bookings = Booking.query.all()
    booking_name = request.form['booking_name']
    email = request.form['email']
    phone_number = request.form['phone_number']
    number_of_guests = request.form['number_of_guests']
    date = request.form['date']
    slot = request.form['slot']
    booking = Booking(booking_name=booking_name, email=email, phone_number=phone_number, booking_date=date, number_of_guests=number_of_guests, slotid=slot)
    db.session.add(booking)
    db.session.commit()
    return render_template('/customer_view/booking_confirmed.jinja')

@restaurant_blueprint.route("/the_good_restaurant/show_booking/<id>") 
def show_booking(id):
    booking = Booking.query.get(id)
    return render_template('/staff-view/show_booking.jinja', booking=booking, id=id)

@restaurant_blueprint.route("/the_good_restaurant/show_booking/<id>/delete", methods=['POST']) 
def delete_booking(id):
    booking = Booking.query.get(id)
    db.session.delete(booking)
    db.session.commit()
    return redirect('/the_good_restaurant/bookings')

@restaurant_blueprint.route('/the_good_restaurant/<id>/edit')
def show_edit(id):
    booking = Booking.query.get(id)
    slots = Slot.query.all()
    return render_template('/staff-view/edit.jinja', slots=slots, booking=booking, id=id)

@restaurant_blueprint.route('/the_good_restaurant/<id>/edit', methods=['POST'])
def update_booking(id):
    booking_name = request.form['booking_name']
    email = request.form['email']
    number_of_guests = request.form['number_of_guests']
    phone_number = request.form['phone_number']
    date = request.form['date']
    
    booking = Booking.query.get(id)
    booking.booking_name = booking_name
    booking.email = email
    booking.number_of_guests = number_of_guests
    booking.phone_number = phone_number
    booking.date = date
    
    db.session.commit()
    return redirect('/the_good_restaurant/bookings')

templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Good Restaurant</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
<header class="header">

    <body class="base-body">
        <div class="header__wrapper">
            <div class="nav-bar">
                <ul class="nav-bar__list">
                    <li class="nav-bar__item">
                        <div class="logo">
                            <span>T.G.R</span>
                        </div>
                    </li>
                    <li><a class="nav-bar__item__li" href="/">Home</a></li>
                    <li><a class="nav-bar__item__li" href="/">About Us</a></li>
                    <li><a class="nav-bar__item__li" href="/the_good_restaurant/bookings">Login</a></li>
                </ul>
            </div>
        </div>
</header>
<div>{% block content %}{% endblock content %}</div>
</body>

</html>

templates/customer_view/book.jinja
{% extends 'base.jinja' %}
{% block content %}
<main class="book">
    <section class="book__content">
        <div class="book__wrapper--date">
            <div class="book__left">
                <h1 class="book__title--date">Select Date</h1>
                <form action="/the_good_restaurant/book_slot" class="book-table" method="POST">
                    <input type="date" name="date" id="date" placeholder="date" required>
                    <input class="submit-btn" type="submit" name="place_booking" id="place_booking"
                        value="See Availability ">
                </form>
            </div>
            <div class="book__img-container">
                <img class="book__img"
                    src="https://cdn.discordapp.com/attachments/931859564863823882/1134853447158616124/Restaurant.jpg">
                <p class="book__img__text">-Our main dining room, built in 1602 and never cleaned once</p>
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/customer_view/book_slot.jinja
{% extends 'base.jinja' %}
{% block content %}


<main class="book">
    <section class="book__content">
        <div class="book__wrapper">
            <div class="book__left">
                <h1 class="book__title">Book Here</h1>
                <form action="/the_good_restaurant/book" class="book-table" method="POST">
                    <input type="text" name="booking_name" id="booking_name" placeholder="Booking Name" required>
                    <input type="email" name="email" id="email" placeholder="Email" required>
                    <input type="text" name="phone_number" placeholder="Phone Number" required>
                    <input type="number" name="number_of_guests" id="number_of_guests" placeholder="Num of Guests"
                        required max="10" min="1">
                    <input type="hidden" name="date" id="date" value="{{date}}" required>
                    <h2 class=" book__title select_slot">Select Time</h2>
                    <select class="select_drop" name="slot" id="slots">
                        {% for slot in slots %}
                        <option value="{{slot.id}}">{{ slot.start_time }}</option>
                        {% endfor %}
                    </select>
                    <input class="submit-btn" type="submit" name="place_booking" id="place_booking"
                        value="Place Booking">
                </form>
            </div>
            <div class="book__img-container">
                <img class="book__img"
                    src="https://cdn.discordapp.com/attachments/931859564863823882/1134853447158616124/Restaurant.jpg">
                <p class="book__img__text">-Our main dining room, built in 1602 and never cleaned once</p>
            </div>
        </div>
    </section>
</main>
{% endblock content %}
</body>

templates/customer_view/booking_confirmed.jinja
<a class="nav-bar__item__li" href="/the_good_restaurant/home">Home</a>
<img src="https://cdn.discordapp.com/attachments/1134939339600703529/1135336367824576655/green_tick.png">
<h1 class="logo">Booking Confirmed</h1>

templates/index.jinja
{% extends 'base.jinja' %}
{% block content %}

<body>
    <main>
        <section class="hero">
            <div class="hero__wrapper">
                <h2 class="hero__welcome">Welcome to</h2>
                <h1 class="hero__title">The Good <br>Restaurant</h1>
                <a href="{{url_for('restaurant.show_book')}}"><button class="book-now-btn">Book Now</button></a>
            </div>
        </section>
    </main>
</body>
{% endblock content %}

templates/staff-view/add_booking.jinja
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Good Restaurant</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

<body class="staff-body">
    <header class="staff-header">
        <div class="staff-header__wrapper">
            <div class="staff-logo">
                <span>T.G.R</span>
                <p class="staff-logo__text">Staff</p>
            </div>
            <ul>
                <li>
                    <div class="logout">
                        <a href="/the_good_restaurant/home">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <div class="staff-view__content">
        <aside class="staff-side-bar">
            <div class="staff-side-bar__wrapper">
                <ul class="staff-side-bar__content">
                    <a href="/the_good_restaurant/bookings">
                        <li class="staff-side-bar__title">Bookings</li>
                    </a>
                    <li class="staff-side-bar__title">View Users</li>
                    <li class="staff-side-bar__title">Add Booking</li>
                </ul>
            </div>
        </aside>
        <div class="add-booking">
            <section class="add-booking__wrapper">
                <form class="book-table" method="POST">
                    <input type="text" name="booking_name" id="booking_name" placeholder="Booking Name" required>
                    <input type="email" name="email" id="email" placeholder="Email" required>
                    <input type="text" name="phone_number" placeholder="Phone Number" required>
                    <input type="number" name="number_of_guests" id="number_of_guests" placeholder="Num of Guests"
                        required max="10" min="1">
                    <input type="date" name="date" id="date" placeholder="date" required>
                    <h2 class="book__title select_slot">Select Time</h2>
                    <select name="slots" id="slots" multiple>
                        {% for slot in slots %}
                        <option>{{ slot.start_time }}</option>
                        {% endfor %}
                    </select>
                    <input class="submit-btn" type="submit" name="place_booking" id="place_booking"
                        value="Place Booking">
                </form>
            </section>
        </div>

templates/staff-view/bookings.jinja
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Good Restaurant</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

<body class="staff-body">
    <header class="staff-header">
        <div class="staff-header__wrapper">
            <div class="staff-logo">
                <span>T.G.R</span>
                <p class="staff-logo__text">Staff</p>
            </div>
            <ul>
                <li>
                    <div class="logout">
                        <a href="/the_good_restaurant/home">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <div class="staff-view__content">
        <aside class="staff-side-bar">
            <div class="staff-side-bar__wrapper">
                <ul class="staff-side-bar__content">
                    <a href="/the_good_restaurant/bookings">
                        <li class="staff-side-bar__title">Bookings</li>
                    </a>
                    <li class="staff-side-bar__title">View Customers</li>
                    <a href="/the_good_restaurant/book">
                        <li class="staff-side-bar__title">Add Booking</li>
                    </a>
                </ul>
            </div>
        </aside>
        <main class="bookings-view">
            <section class="bookings-view__wrapper">
                <div class="bookings-view__titles">
                    <h2 class="bookings-view__titles--title">Bookings:</h2>
                </div>
                <div class="bookings-view__content">
                    {% for booking in bookings %}
                    <a class="booking-card-link" href="/the_good_restaurant/show_booking/{{booking.id}}">
                        <ul class="bookings-view__booking">
                            <li class="bookings-view__content--titles">Name: <span
                                    class="bookings-view__content--titles--not-bold"><em>{{ booking.booking_name
                                        }}</em></span></li>
                            <li class="bookings-view__content--titles">Number of Guests: <span
                                    class="bookings-view__content--titles--not-bold"><em>{{ booking.number_of_guests
                                        }}</em></span></li>
                            <li class="bookings-view__content--titles">Date: <span
                                    class="bookings-view__content--titles--not-bold"><em>{{
                                        booking.booking_date.strftime("%d/%m/%Y")
                                        }}</em></span></li>
                        </ul>
                    </a>
                    {% endfor %}
                </div>
            </section>
        </main>
    </div>
</body>

templates/staff-view/edit.jinja
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Good Restaurant</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

<body class="staff-body">
    <header class="staff-header">
        <div class="staff-header__wrapper">
            <div class="staff-logo">
                <span>T.G.R</span>
                <p class="staff-logo__text">Staff</p>
            </div>
            <ul>
                <li>
                    <div class="logout">
                        <a href="/the_good_restaurant/home">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <div class="staff-view__content">
        <aside class="staff-side-bar">
            <div class="staff-side-bar__wrapper">
                <ul class="staff-side-bar__content">
                    <a href="/the_good_restaurant/bookings">
                        <li class="staff-side-bar__title">Bookings</li>
                    </a>
                    <li class="staff-side-bar__title">View Customers</li>
                    <a href="/the_good_restaurant/book">
                        <li class="staff-side-bar__title">Add Booking</li>
                    </a>
                </ul>
            </div>
        </aside>
        <div class="edit__form">
            <h1 class="edit__form--title">Edit: {{ booking.booking_name }}</h1>
            <form class="book-table" method="POST">
                <input type="text" name="booking_name" id="booking_name" placeholder="Booking Name"
                    value="{{booking.booking_name}}" required>
                <input type="email" name="email" id="email" placeholder="Email" required>
                <input type="text" name="phone_number" placeholder="Phone Number" required>
                <input type="number" name="number_of_guests" id="number_of_guests" placeholder="Number of Guests"
                    required max="10" min="1">
                <input type="date" name="date" id="date" placeholder="date" required>
                <h2 class="book__title select_slot">Select Time</h2>
                <select class="select_drop" name="slot" id="slots">
                    {% for slot in slots %}
                    <option value="{{slot.id}}">{{ slot.start_time }}</option>
                    {% endfor %}
                </select>
                <input class="submit-btn" type="submit" name="place_booking" id="place_booking" value="Update Booking">
            </form>
        </div>

templates/staff-view/show_booking.jinja
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Good Restaurant</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

<body class="staff-body">
    <header class="staff-header">
        <div class="staff-header__wrapper">
            <div class="staff-logo">
                <span>T.G.R</span>
                <p class="staff-logo__text">Staff</p>
            </div>
            <ul>
                <li>
                    <div class="logout">
                        <a href="/the_good_restaurant/home">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <main class="staff-view__content">
        <aside class="staff-side-bar">
            <div class="staff-side-bar__wrapper">
                <ul class="staff-side-bar__content">
                    <a href="/the_good_restaurant/bookings">
                        <li class="staff-side-bar__title">Bookings</li>
                    </a>
                    <li class="staff-side-bar__title">View Customers</li>
                    <a href="/the_good_restaurant/book">
                        <li class="staff-side-bar__title">Add Booking</li>
                    </a>
                </ul>
            </div>
        </aside>
        <div class="bookings-view">
            <section class="bookings-view__wrapper">
                <div class="bookings-view__titles">
                    <h2 class="bookings-view__titles--title">{{ booking.booking_name }}</h2>
                </div>
                <div class="bookings-view__details__box">
                    <div class="bookings-view__details__box__wrapper">
                        <h2 class="details__box__title">Booking Details</h2>
                        <ul class="bookings-view__details__box__content">
                            <li class="details__box__item"><span style="font-weight: bolder;">Booked for:</span> {{
                                booking.booking_date.strftime("%d/%m/%Y")}}</li>
                            <li class="details__box__item"><span style="font-weight: bolder;">Slot: </span>{{
                                booking.slot.start_time }}</li>
                            <li class="details__box__item"><span style="font-weight: bolder;">Email: </span>{{
                                booking.email }}</li>
                            <li class="details__box__item"><span style="font-weight: bolder;">Tel:</span> {{
                                booking.phone_number}}</li>
                            <li class="details__box__item"><span style="font-weight: bolder;">Number of Guests:
                                </span>{{
                                booking.number_of_guests }}</li>
                            <div class="booking-buttons">
                                <form action="/the_good_restaurant/show_booking/{{booking.id}}/delete" method="post">
                                    <li><span style="font-weight: bolder;"><button type="submit"
                                                class="delete-btn">Delete
                                                Booking</button>
                                    </li>
                                </form>
                                <a href="/the_good_restaurant/{{booking.id}}/edit">
                                    <li><span style="font-weight: bolder;"><button class="amend-btn">Amend
                                                Booking</button>
                                    </li>
                                </a>
                            </div>
                        </ul>
                    </div>
                </div>
            </section>
        </div>
    </main>
</body>

</html>